### PR TITLE
tests

### PR DESCRIPTION
**Pull request by bidwolf**
This pull request includes several changes related to the carousel component and testing in the project. It aims to improve test coverage and refactor the carousel component to utilize hooks.

Changes Made:
- [x] Added "vitest" to the dependency tree and created the "vitest" workspace.
- [x] Refactored the "package.json" file to remove void scripts of tests.
- [x] Added "@testing-library" to the dependency tree.
- [x] Added "@vitest/coverage-c8" to provide coverage.
- [x] Added "js-dom" to the React package to provide tests related to the DOM.
- [x] Added tests and lint scripts to run before release.
- [x] Refactored the carousel component to utilize hooks.
- [x] Added "@testing-library/react-hooks" to the project.
- [x] Added tests to the carousel component and "useCarousel" hook.
- [x] Added tests for the button component.
- [x] Updated dependencies in the documentation.
- [x] Corrected tests for swipe power in the "usecarousel" module.

Please review and consider merging these changes into the main branch.

### CODE REVIEW

**Review by bidwolf — COMMENTED** [review]
Não se assustem com números, basicamente adicionei os testes e refatorei algumas partes do código para outros arquivos

**Comment by bidwolf** [comment]
### Update

- [x] Added tests for all components on the react package
- [x] Setup tests on the web component

**Review by ooBraia — APPROVED** [review]
ok!

**Review by ooBraia — APPROVED** [review]
ok!

**Review by ooBraia — APPROVED** [review]
ok!

**Review by ooBraia — APPROVED** [review]
ok!

**Review by ooBraia — APPROVED** [review]
ok!

**Review by fredzolio — APPROVED** [review]

**Pull request merged**
