### PR TITLE
Feat/input radio

### PR DESCRIPTION
**Pull request by bidwolf**
# Pull Request Description:

This pull request includes several commits related to the development, testing, and documentation of the radio component. Here are the details of the commits included in this pull request:

## Preview

Look for the preview of the component:

Unselected|Primary|Secondary|Tertiary
:---:|:---:|:---:|:---: 
image|image|image|image

### feat(radio): created atomic radio component

This commit introduces the implementation of a new atomic radio component. The radio component allows users to select a single option from a list of choices.

### test(radio): added tests for the radio component

This commit adds unit tests for the radio component. These tests ensure the correct functionality and behavior of the element, enhancing its overall reliability.

### docs(radio): added stories on the storybook for the radio component

This commit focuses on the documentation aspect and adds stories to the Storybook for the radio component. Storybook provides an interactive showcase of UI components, allowing developers and designers to understand and explore the radio component's usage.

### docs(radio): bump the version of codelife-ui package

This commit updates the version of the codelife-ui package used in the project. Bumping the version ensures compatibility and synchronization with other dependencies and enables utilizing the latest features and improvements.
This pull request introduces a new atomic radio component, enhances its reliability through testing, and provides detailed documentation and version synchronization for smooth integration into the project.

### CODE REVIEW

**Review by fredzolio — APPROVED** [review]
Bacana

**Review by PedroRonzani18 — APPROVED** [review]
Ok!

**Review by ooBraia — APPROVED** [review]
ok!

**Review by geovanelelis — APPROVED** [review]
Ok

**Review by geovanelelis — APPROVED** [review]

**Review by JoaoPedroSilvaSantos — APPROVED** [review]
LINDO

**Pull request merged**
